config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :users, only: [:index, :show] do
    get :favorites, on: :member
  end
  
  resources :posts do
    resource :favorites, only: [:create, :destroy]
  end
  root 'posts#index'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	belongs_to :user
	belongs_to :post

	validates :user, presence: true
	validates :user_id, uniqueness: { scope: :post_id}
	validates :post, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :favorites, dependent: :destroy

	validates :body, presence: true, length: { in: 1..140}
	validates :user_id, presence: true

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	default_scope -> {order(created_at: :desc)}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # validates :post, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      # sign_upのときに、nameも許可する
      devise_parameter_sanitizer.for(:sign_up) << :name
      #  account_updateのときに、nameも許可する
      devise_parameter_sanitizer.for(:account_update) << :name
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@favorite = current_user.favorites.build(post: @post)

		if @favorite.save
			redirect_to posts_url, notice: "お気に入り登録をしました"
		else
			redirect_to posts_url, alert: "このツイートはお気に入り登録できません"
		end
	end

	def destroy
		@favorite = current_user.favorites.find_by!(post_id: params[:post_id])
		@favorite.destroy
		redirect_to posts_url, notice: "お気に入りを解除しました"
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: '投稿できました！！' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_url, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        @posts = Post.all
        format.html { render :index }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  	@post = Post.new
  end

  def favorites
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Websuku</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
        <nav>
            <% if user_signed_in? %>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
                <%= link_to 'マイページ', user_path(current_user) %>
            <% else %>
                <%= link_to 'サインアップ', new_user_registration_path %>
                <%= link_to 'ログイン', new_user_session_path %>
            <% end %>
        </nav>
  </header>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to '見る', @post %> |
<%= link_to '戻る', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
 
<div id="post-body">
    <div class="container">
        <div class="col-xs-4.left-body">
            <% if signed_in? %>
                <div class="panel">
                    <div class="panel-body">
                        <%= link_to user_path(current_user), class: "user" do %>
                            <span class="user-name">
                                
                            </span>
                            <span class="user-id">
                                @<%= current_user.name %>
                            </span>
                        <% end %>
                        <div class="user-acivity">
                            <div class="row">
                                <div class="col-xs-4.posts-num">
                                    <div class="text">
                                        つぶやき
                                    </div>
                                    <div class="num">
                                        <%= link_to current_user.posts.count, user_path(current_user) %>
                                    </div>
                                </div>
                                <div class="col-xs-4.follow-num">
                                    <div class="text">
                                        フォロー
                                    </div>
                                    <div class="num">
                                        0
                                    </div>
                                </div>
                                <div class="col-xs-4.follower-num">
                                    <div class="text">
                                        フォロワー
                                    </div>
                                    <div class="num">
                                        0
                                    </div>
                                </div>
                            </div>
                            
                        <%= render "form" %>    
                        
                        </div>
                    </div> 
                </div>
            <% end %>
        </div>
        <div class="col-xs-8.right-body">
            <div class="list-group">
                <%= div_for @posts, class: "list-group-item" do |t| %>
                    <h4 class="user">
                        <span class="user-name">
                            
                        </span>
                        <span class="user-id">
                            
                        </span>
                        <span class="time.pull-right">
                            <%= distance_of_time_in_words_to_now(t.created_at) %>
                        </span>
                        <div class="clear">
                        </div>
                    </h4>
                    <div class="post-body">
                        <p>
                            <%= t.body %>
                            <% if t.favorited_by?(current_user) %>
                            <%= link_to 'イイネシナイ', post_favorites_path(t), method: :delete %>
                            <% else %>
                              <%= link_to 'iine', post_favorites_path(t), method: :post %>

                            <% end %>
                        </p>
                        <div class="content-footer">
                                
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to '戻る', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to '編集', edit_post_path(@post) %> |
<%= link_to '戻る', posts_path %>

app/views/users/index.html.erb
<h1>Usres#index</h1>
<p>Find me in app/views/usres/index.html.erb</p>

app/views/users/show.html.erb
<h1>マイページ</h1>
<h2><%= @user.name %>@<%= @user.name%></h2>

<%= render 'posts/form' %> 

<% @user.posts.each do |post| %>
		<h4 class="user-name"><span><%= post.user.try(:name) %></span>
    	<span class="user-id">@<%= post.user.try(:name) %></span></h4>
        <p><%= post.body %></p>
        <span><%= link_to '見る',post_path(post) %></span>
        <% if user_signed_in? && current_user.id == post.user.id%>
        	<sapn><%= link_to '編集', edit_post_path(post) %></span>
        	<span><%= link_to '削除', post, method: :delete, data: { confirm: '本当に削除しますか?' } %></span>
        <% end %>
<% end%>
<ul class="nav.nav-tabs">
	<li class="active">
		<% link_to user_path(@user) do %>
			<div class="text">
				つぶやき
			</div>
			<div class="num">
				<%= @user.posts.count %>
			</div>
		<% end %>	
	</li>
	<li>
		<%= link_to nil do %>
			<div class="text">
				フォロー
			</div>
			<div class="num">
				0
			</div>
		<% end %>	
	</li>
	<li>
		<%= link_to nil do %>
			<div class="text">
				お気に入り
			</div>
			<div class="num">
				0
			</div>
		<% end %>
	</li>
</ul>
<div class="list-group">
	<% if @user.posts.empty? %>
		<div class="list-group-item">
			まだツイートはありません
		</div>
	<% end %>
	<%= div_for @user.posts, class: "list-group-item" do |t| %>
		<h4 class="user">
			<span class="user-name">
				<%= link_to t.user.name, user_path(t.user) %>
			</span>
			<span class="user-id">
				<%= t.user.name %>
			</span>
			<span class="time.pull-right">
				<%= distance_of_time_in_words_to_now(t.created_at) %>
			</span>
			<div class="clear">
				
			</div>
		</h4>
		<div class="post-body">
			<p>
				<%= t.body %>
			</p>
		</div>
	<% end %>
</div>